version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=muchofiesta_usr
      - POSTGRES_PASSWORD=muchofiesta_pw
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/muchofiesta_db
      - SPRING_DATASOURCE_USERNAME=muchofiesta_usr
      - SPRING_DATASOURCE_PASSWORD=muchofiesta_pw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - POSTGRES_DB=$YOUR_DB_NAME
    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"